"""empty message

Revision ID: 750fbeb016c5
Revises: e26ab244c5e6
Create Date: 2021-04-02 15:56:25.552643

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '750fbeb016c5'
down_revision = 'e26ab244c5e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('coin', sa.Column('fluctate_rate_24H', sa.Float(), nullable=True))
    op.drop_column('coin', 'fluctate_24H_rate')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('coin', sa.Column('fluctate_24H_rate', sa.FLOAT(), nullable=True))
    op.drop_column('coin', 'fluctate_rate_24H')
    # ### end Alembic commands ###
