"""empty message

Revision ID: d2e35ddf3951
Revises: 709c4b821aa6
Create Date: 2021-04-02 18:22:14.711294

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd2e35ddf3951'
down_revision = '709c4b821aa6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comment')
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'coin_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('coin_id', sa.INTEGER(), nullable=True))
    op.create_foreign_key(None, 'user', 'coin', ['coin_id'], ['id'])
    op.create_table('comment',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('content', sa.TEXT(), nullable=False),
    sa.Column('create_date', sa.DATETIME(), nullable=False),
    sa.Column('modify_date', sa.DATETIME(), nullable=True),
    sa.Column('coin_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['coin_id'], ['coin.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
