"""empty message

Revision ID: e26ab244c5e6
Revises: 4333f0e5db77
Create Date: 2021-04-02 15:51:09.055696

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e26ab244c5e6'
down_revision = '4333f0e5db77'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('coin', sa.Column('acc_trade_value', sa.Float(), nullable=True))
    op.add_column('coin', sa.Column('acc_trade_value_24H', sa.Float(), nullable=True))
    op.add_column('coin', sa.Column('prev_closing_price', sa.Float(), nullable=True))
    op.add_column('coin', sa.Column('units_traded_24H', sa.Float(), nullable=True))
    op.drop_column('coin', 'sell_price')
    op.drop_column('coin', 'volume_1day')
    op.drop_column('coin', 'volume_7day')
    op.drop_column('coin', 'buy_price')
    op.drop_column('coin', 'average_price')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('coin', sa.Column('average_price', sa.FLOAT(), nullable=True))
    op.add_column('coin', sa.Column('buy_price', sa.FLOAT(), nullable=True))
    op.add_column('coin', sa.Column('volume_7day', sa.FLOAT(), nullable=True))
    op.add_column('coin', sa.Column('volume_1day', sa.FLOAT(), nullable=True))
    op.add_column('coin', sa.Column('sell_price', sa.FLOAT(), nullable=True))
    op.drop_column('coin', 'units_traded_24H')
    op.drop_column('coin', 'prev_closing_price')
    op.drop_column('coin', 'acc_trade_value_24H')
    op.drop_column('coin', 'acc_trade_value')
    # ### end Alembic commands ###
